// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


#[derive(diesel_derive_enum::DbEnum)]
#[ExistingTypePath = "crate::schema::sql_types::PaymentAccountAccountTypeEnum"]
pub enum PaymentAccountTypeEnum {
	Debit,
	Savings,
	Credit,
}

#[derive(diesel_derive_enum::DbEnum)]
#[ExistingTypePath = "crate::schema::sql_types::TransactionCategoryCategoryTypeEnum"]
pub enum TransactionCategoryTypeEnum {
	Income,
	Expense,
}


use chrono::NaiveDate;
#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(AccountID))]
pub struct CreditAccount {
    pub AccountID: u8,
    pub CreditLimit: f64,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(CategoryID))]
pub struct ExpenseCategory {
    pub CategoryID: u8,
    pub MonthlyBudget: f64,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(CategoryID))]
pub struct IncomeCategory {
    pub CategoryID: u8,
    pub MonthlyExpected: f64,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(JobID))]
pub struct Job {
    pub JobID: u8,
    pub JobName: String,
    pub Wage: f64,
    pub ExpectedMonthlyHours: u8,
    pub ExpectedMonthlyMissHours: u8,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(CategoryID))]
pub struct JobIncome {
    pub CategoryID: u8,
    pub JobID: u8,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(AccountID))]
pub struct PaymentAccount {
    pub AccountID: u8,
    pub AccountName: String,
    pub AccountType: /* TODO: unknown type PaymentAccountAccountTypeEnum */,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(AccountID, MinBalanceForRate))]
pub struct SavingsAccount {
    pub AccountID: u8,
    pub MinBalanceForRate: f64,
    pub InterestRate: f64,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(TransactionID))]
pub struct Transaction {
    pub TransactionID: u32,
    pub TransactionDate: NaiveDate,
    pub Description: String,
    pub Amount: f64,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(TransactionID))]
pub struct TransactionAccount {
    pub TransactionID: u32,
    pub AccountID: u8,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(CategoryID))]
pub struct TransactionCategory {
    pub CategoryID: u8,
    pub CategoryName: String,
    pub CategoryType: /* TODO: unknown type TransactionCategoryCategoryTypeEnum */,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(TransactionID))]
pub struct TransactionInstanceCategory {
    pub TransactionID: u32,
    pub CategoryID: u8,
}

